Models/SOL.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace MvcSOL.Models
{
    public class SOL
    {
        [Key]
        public int caseID { get; set; }
        public string Case { get; set; }
        public string Atty { get; set; }
        public DateTime SOLDate { get; set; }
    }

    public class SOLDBContext : DbContext
    {
        public DbSet<SOL> SOLs { get; set; }
    }

}

Controllers/SOLController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcSOL.Models;

namespace MvcSOL.Controllers
{
    public class SOLController : Controller
    {
        private SOLDBContext db = new SOLDBContext();

        //
        // GET: /SOL/

        public ActionResult Index()
        {
            return View(db.SOLs.ToList());
        }

        //
        // GET: /SOL/Details/5

        public ActionResult Details(int id = 0)
        {
            SOL sol = db.SOLs.Find(id);
            if (sol == null)
            {
                return HttpNotFound();
            }
            return View(sol);
        }

        //
        // GET: /SOL/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /SOL/Create

        [HttpPost]
        public ActionResult Create(SOL sol)
        {
            if (ModelState.IsValid)
            {
                db.SOLs.Add(sol);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(sol);
        }

        //
        // GET: /SOL/Edit/5

        public ActionResult Edit(int id = 0)
        {
            SOL sol = db.SOLs.Find(id);
            if (sol == null)
            {
                return HttpNotFound();
            }
            return View(sol);
        }

        //
        // POST: /SOL/Edit/5

        [HttpPost]
        public ActionResult Edit(SOL sol)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sol).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(sol);
        }

        //
        // GET: /SOL/Delete/5

        public ActionResult Delete(int id = 0)
        {
            SOL sol = db.SOLs.Find(id);
            if (sol == null)
            {
                return HttpNotFound();
            }
            return View(sol);
        }

        //
        // POST: /SOL/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            SOL sol = db.SOLs.Find(id);
            db.SOLs.Remove(sol);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        public ActionResult SearchIndex(string id)
        {
            string searchString = id;
            var sols = from s in db.SOLs
                       select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                sols = sols.Where(s => s.Case.Contains(searchString));
            }

            return View(sols);
        }


    }
}

Views/SOL/Create.cshtml
@model MvcSOL.Models.SOL

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>SOL</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Case)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Case)
            @Html.ValidationMessageFor(model => model.Case)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Atty)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Atty)
            @Html.ValidationMessageFor(model => model.Atty)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SOLDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SOLDate)
            @Html.ValidationMessageFor(model => model.SOLDate)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/SOL/Delete.cshtml
@model MvcSOL.Models.SOL

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>SOL</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Case)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Case)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Atty)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Atty)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.SOLDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SOLDate)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Views/SOL/Details.cshtml
@model MvcSOL.Models.SOL

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>SOL</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Case)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Case)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Atty)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Atty)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.SOLDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SOLDate)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.caseID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/SOL/Edit.cshtml
@model MvcSOL.Models.SOL

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>SOL</legend>

        @Html.HiddenFor(model => model.caseID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Case)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Case)
            @Html.ValidationMessageFor(model => model.Case)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Atty)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Atty)
            @Html.ValidationMessageFor(model => model.Atty)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SOLDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SOLDate)
            @Html.ValidationMessageFor(model => model.SOLDate)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/SOL/Index.cshtml
@model IEnumerable<MvcSOL.Models.SOL>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Case)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Atty)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SOLDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Case)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Atty)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SOLDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.caseID }) |
            @Html.ActionLink("Details", "Details", new { id=item.caseID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.caseID })
        </td>
    </tr>
}

</table>

Views/SOL/SearchIndex.cshtml
@model IEnumerable<MvcSOL.Models.SOL>

@{
    ViewBag.Title = "SearchIndex";
}

<h2>SearchIndex</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
    @using (Html.BeginForm("SearchIndex","SOL",FormMethod.Get)){   
         <p> Title: @Html.TextBox("id")
         <input type="submit" value="Filter" /></p>
        }

<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Case)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Atty)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SOLDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Case)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Atty)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SOLDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.caseID }) |
            @Html.ActionLink("Details", "Details", new { id=item.caseID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.caseID })
        </td>
    </tr>
}

</table>